### ISSUE TITLE
Storefront / Product page - fix scroll position at the top when select other products,

### ISSUE THREAD

**Issue by primSirirnit** [zaviagodev/e_commerce_store#38]
On the product detail page, when we scroll down to the bottom Press to select other products, it will bring up a new page, but the position is not at the top. so fix scroll position at the top when select other products

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120098635/642ac4db-fd4c-4161-bfba-24e2d9a2497a)

**Comment by primSirirnit** [comment]
Done - fix scroll position at the top when select other products,

But have issue on sticky P'Mark - Mark said It takes about 30 minutes.

**Comment by primSirirnit** [comment]
Can't fix sticky and fix scroll  - sticky is work the position is not correct , The selected image is not at the top.

**Comment by primSirirnit** [comment]
The picture does not adjust to the screen. make large

On site 
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120098635/78f5a904-819c-41f6-901d-be694c66df74)

On design 


![Image](https://github.com/zaviagodev/e_commerce_store/assets/120098635/7fbb26a3-fb81-43e5-b34e-ee97be24501e)

**Comment by MarkSuttirak** [comment]
![image](https://github.com/zaviagodev/e_commerce_store/assets/116248336/7e2f4f3f-a995-43c9-94f0-88c2e416085e)

The image above shows two different images about the sticky position. I have already written the class 'sticky' for two sides, left small image group and product detail, to make it show a top sticky position while scrolling.

The left image: adding 'sticky top-4' for the left small image group to set the top as '16px' when scrolling so that it creates a top space.
The right image: no sticky position after scrolling.

![image](https://github.com/zaviagodev/e_commerce_store/assets/116248336/6cff3318-29d9-4cc5-bfbf-37d538dd0215)

From the code I sent as an image, I'm not sure that it causes the issue of no sticky position or not, because the tag that I wrote before was <img>, which there was no issue of sticky position.

**Comment by MarkSuttirak** [comment]
> The picture does not adjust to the screen. make large
> 
> On site ![Image](https://private-user-images.githubusercontent.com/120098635/300736263-78f5a904-819c-41f6-901d-be694c66df74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTQ1ODgsIm5iZiI6MTcwNjc1NDI4OCwicGF0aCI6Ii8xMjAwOTg2MzUvMzAwNzM2MjYzLTc4ZjVhOTA0LTgxOWMtNDFmNi05MDFkLWJlNjk0YzY2ZGY3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQwMjI0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzBhMWM3ZGVjNzdlMmIzMzM0NjUyNmYwMzljZjQ2ZGE3NTJlMjBjMDk1MTgxOWJlM2MyMWM2ZWMwMzBjMmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ldvCV1gSD_wPaMs-_uDISLmYvcDbDf6WemNIOgadsqc)
> 
> On design
> 
> ![Image](https://private-user-images.githubusercontent.com/120098635/300736625-7fbb26a3-fb81-43e5-b34e-ee97be24501e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTQ1ODgsIm5iZiI6MTcwNjc1NDI4OCwicGF0aCI6Ii8xMjAwOTg2MzUvMzAwNzM2NjI1LTdmYmIyNmEzLWZiODEtNDNlNS1iMzRlLWVlOTdiZTI0NTAxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQwMjI0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODljMTZhNzBkMGM4MGIzZTAzNWE5YjA5MjYyYjI1OTY0ZDVlY2FkMjIxYTIzMTkyMjg4NGEwNGMyYzAwOWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jXpBdHpfr3zx0XxZQcD9O_KTjVDUxTm2tYlKvnU2hq4)

If there is only one image, I can set the image as full width (100%). But if there are more than one image, I can only set the image width as 500px. because the images will be typically small if I set the width as 100%.
